### ISSUE TITLE
REQUEST: Varying patch times for wound type

### ISSUE THREAD

**Issue by Narfmeister** [willithappen/eams#10]
**Is your feature request related to a problem? Please describe.**
Seems odd that a bad wound takes the same amount of time as a 'minor' wound.

**Describe the solution you'd like**
Adjust patch time based on wound type.
The velocity wound at present, takes the current time, where as the less serious would be shorter.

**Describe alternatives you've considered**
Shorten treatment time, but that would result in an overall drawback.

**Additional context**
Would provide more immersion and also faster treatment for light injuries.

**Comment by willithappen** [comment]
Feature completed
