### ISSUE TITLE
BUG: Issues with vehicle loading

### ISSUE THREAD

**Issue by Narfmeister** [willithappen/eams#13]
**Is your feature request related to a problem? Please describe.**
After being loaded into a vehicle, the loaded passenger's camera twitches very fast. 
Unsure if part of this or if I was unloaded but I was also dropped onto the ground, then teleported into the vic before being dropped onto the ground again and eventually dying.

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/issues/21

**Comment by willithappen** [comment]
Fixed
