### ISSUE TITLE
BUG: Pain issues

### ISSUE THREAD

**Issue by Broche96** [willithappen/eams#15]
As 1-1-2 Bravo was setting up on a mountain top in phase 2, PTE(P) RobZombie, LCPL Reckers and PTE(P) Broche were over pressured by a friendly tank firing behind us, injuring all three during. We had pain for the remainder of the op with no known way of healing. W even went down and were revived and it was still persisting.

**Comment by willithappen** [comment]
By "pain" do you mean your character was moaning or you were walking slower or your screen had the blood effect?

There is no pain handling at the moment so it may be a vanilla response to something.

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/issues/17
https://github.com/willithappen/eams/commit/7f72e9e3456bbc8938b1f4023194a941ef378cae
https://github.com/willithappen/eams/commit/1e65746e9e854a983c1020e493b367f770c2311f
