### ISSUE TITLE
BUG: Bandages Breaking upon Return

### ISSUE THREAD

**Issue by 13lacklight** [willithappen/eams#16]
When i was bandaging a patient, they died half way through and the bandage was returned to my inventory. However i did not have any bandages left and was using the patients. The bandage it returned to me after they died i could not interact with. i couldnt drop it or move it to my chest rig. Picking up more also did not help and just locked them as well. Also when i got shot later with this issue, i could not bring up the medical menu or anything despite having 13(locked) bandages in my shirt. The section medic was able to fix me but obviously this is not ideal as the issue persisted.

Need to review whatever mechanism is behind the "return bandage when patient dies" bit of the code as it either lacks a provision for if the player dies and youre using their bandage or its broken.

Not return bandage if they die and youre using their bandages. Means bandages might disapear as they get used up even though they did nothing, but a dead person is hardly going to care.

**Comment by willithappen** [comment]
Cannot reproduce. Please re-open if you can find a repro step.
