### ISSUE TITLE
BUG: EAMS menu closing after each action

### ISSUE THREAD

**Issue by ferdinandwinters** [willithappen/eams#18]
I stepped in as section medic tonight, each action I took closed my EAMS menu and would require me to reopen it to go again. I will link Op video with timestamp once it has finished uploading so you can take a look.

**PTE(P) Pants**

https://drive.google.com/file/d/1_A0WzuHOZJPeGXHptoRFBH7A6bAILH_R/view?usp=sharing

**Comment by Chrisone4** [comment]
Unfortunatly, it's not a bug.

**Comment by ferdinandwinters** [comment]
I doubt it would be a feature, but if it is, it is.

**Comment by Chrisone4** [comment]
I'd say the Menu is still WIP.

**Comment by ferdinandwinters** [comment]
Added link to clipped video of menu closing. Maybe progress bar is interfering with the EAMS menu.

**Comment by willithappen** [comment]
The menu is currently supposed to close when the progress bar comes up. This is so the progress bar can be handled properly.

Its not really a "bug" that the menu doesn't re-open but we can add it auto re-opening if patching was a success but not re-open if you deliberately exited the patching.

**Comment by willithappen** [comment]
Added
