### ISSUE TITLE
Bugs: A bunch of bugs seen/recorded.

### ISSUE THREAD

**Issue by Chrisone4** [willithappen/eams#19]
https://drive.google.com/open?id=1oXwxsRUCSt196hKa9vdsWwK2HRS1UwFq
HamMan had 0 wounds, but was unable to move properly and limbs had a "wounded appearance"; However, shooting him in the leg fixed that issue. Also, apparently 1 close range pistol shot causes 2x Velocity and 1x Minor.
Also seen in that clip is AlienPunch's body glitching out similar to the Ace Medical issues from before. (Which can also be seen in the following clip).
https://drive.google.com/open?id=1Cd9N8Cxy5rM8PHQiK_K126GGOanF1GwK

https://drive.google.com/open?id=1pXAx-p3-Qu2XNUaudsI02ly9LpE6QaL2
Sliding on ground bug is also still a thing.

https://drive.google.com/open?id=1DPWLpqyesTjp07LafwewYcXVLZ9Mj0EF
The last clip is probably not EAMS related, but gives some context to what happened to Gaz at the end and it did happen during the mission.

**Comment by willithappen** [comment]
These bugs should mostly all be fixed other than body positioning. This seems to be an ArmA bug not necesarily an EAMS issue.
