### ISSUE TITLE
ToDo: Correct color selection for wounds when interacting

### ISSUE THREAD

**Issue by willithappen** [willithappen/eams#2]
Also need to tweak thresholds for different colors

**Comment by 13lacklight** [comment]
A red to yellow system would be good for measuring severity at a glance, last Sunday it was difficult as blue was healed in previous ace medical so some people would stop bandaging once they got that. Also once you’ve sorted out colouring and how things are gonna go I’d be down to help put together a how too as there are little bits that aren’t really explained atm.

**Comment by Jazz-Daniels** [comment]
Id just like to know what the colours meant. Red bad, yellow less bad, blue okay? White done? There was no communication of that I don't think.

**Comment by willithappen** [comment]
Fixed
