### ISSUE TITLE
BUG: Issues with vehicle loading

### ISSUE THREAD

**Issue by ferdinandwinters** [willithappen/eams#21]
![image](https://user-images.githubusercontent.com/25633642/80914228-8e911780-8d8d-11ea-86c8-fa6c271bfa34.png)

It was Englishman during the move from phase 2 to phase 3. We still managed to get him in eventually. Will review video footage and link appropriate timestamp.

https://drive.google.com/file/d/12HybLcl3R8NeF49PK-KO9DhjJLeWJV2b

**PTE(P) Pants**

**Comment by ferdinandwinters** [comment]
Added link to snipped video, reports Englishman is too far away, maybe he is. Also didn't help that I pressed "Unload Incapacitated"

**Comment by willithappen** [comment]
Merged with https://github.com/willithappen/eams/issues/13
