### ISSUE TITLE
Bug: Self Interaction key not working to open Medical Menu

### ISSUE THREAD

**Issue by Chrisone4** [willithappen/eams#24]
Watching Wizz's stream back and he did not have the ability to open his Medical Menu via Ace self interaction. However, he could access the Medical menu on other players.
https://www.twitch.tv/videos/609889734
01:01:00 Timestamp

**Comment by willithappen** [comment]
You're not supposed to be able to open yourself via self interaction. There is a keybind for this for a reason.
