### ISSUE TITLE
BUG: Fall damage error message

### ISSUE THREAD

**Issue by Wolflec** [willithappen/eams#26]
Upon falling from a large object, (both into water and on land) the following error message appeared on screen:

![20200508225125_1](https://user-images.githubusercontent.com/49945534/81407588-06d94d80-917f-11ea-8808-45cbd9a4f6fb.jpg)
![20200508223517_1](https://user-images.githubusercontent.com/49945534/81407599-0c369800-917f-11ea-8194-98ffcb546f6d.jpg)

Wounds seem to appear as normal but it does not incapacitate you. (With the current settings to damage taken this makes sense). Obviously, falling from a large height isn't going to occur during operations that often, but the error message is not ideal.

**Comment by willithappen** [comment]
Easy fix. I left some legacy code that was an early way I was handling different wounds.
It wasn't causing errors for me as I hadn't jumped off a building yet.

**Comment by willithappen** [comment]
Resolved in https://github.com/willithappen/eams/commit/520455a915a4cc094d1bec159d5c569997e27ba6
