### ISSUE TITLE
BUG: Wounds kept after dying.

### ISSUE THREAD

**Issue by Chrisone4** [willithappen/eams#29]
Seemingly instant dying super fast causes your wounds to carry over to your respawned body.
https://drive.google.com/open?id=1KlY-pGCi_MKjuhCGfrxZOcNXlS1NbJ2J

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/blob/master/functions/revive/fn_reviveDamageReset.sqf#L20

Issue due to un-updated reset values. Should instead be;

player setVariable [format ["EAMS-%1Wounds","All"],[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]];


Fixed in dev

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/commit/d32b1c1b9ae8a70c238d6032843b474796e58c4f
