### ISSUE TITLE
REQUEST: Medical Menu

### ISSUE THREAD

**Issue by Jazz-Daniels** [willithappen/eams#3]
Doesn't have to be the full Medical menu that we are used to. Even a picture of the person in the top left with the areas that are currently affected by wounds. 

Although a full medical menu would be nice for those of us who are used to using it.

**Comment by willithappen** [comment]
![arma3_x64_2020-04-28_09-58-32](https://user-images.githubusercontent.com/26050284/80432238-f4694380-8936-11ea-95cc-b4bd89677b5c.png)

First mockup of medical menu.

Please note that GUI's in arma are a giant cunt so for now, it's really not pretty but it will be functional.

This will replace the ace interactions for various performance reasons (sorry non-menu people) for now.

If someone can draw up something in their photo editor/drawing tool of choice a pretty menu, i can do my best to implement that in future

**Comment by 13lacklight** [comment]
I can see what I can do but might take some fiddling, willing to help out wherever possible.

**Comment by Jazz-Daniels** [comment]
I think renaming it to torso over chest is a little bit more vague and covers stomach area as well.

**Comment by willithappen** [comment]
Added
