### ISSUE TITLE
Remember last selected limb upon menu reopen

### ISSUE THREAD

**Issue by ferdinandwinters** [willithappen/eams#30]
Bit frustrating when treating someone that when the EAMS menu reopens that it defaults to the chest. If it is possible it would be nice if EAMS could remember the last limb you worked on and then default back to that limb.

If the last treatment makes the limb green then it could default back to the chest over the previously treated limb.

**PTE(P) Pants**

**Comment by willithappen** [comment]
Added function for remembering last selected wound.
