### ISSUE TITLE
Addition of Signs and Symptoms

### ISSUE THREAD

**Issue by Wolflec** [willithappen/eams#6]
Differential diagnosis is an interest and challenging part of the medical system that has its place in previous practice of treatment and interventions. Vital signs can not be simulated the same as before, the solution is to create a system that is less demanding on the server. Vital signs should be representative of the changes that occurring during specific injuries and conditions, not the other way around. For example if you were to check the vitals signs of a patient it would choose a random number depending on the condition:

>Player not injured
HR: 60-100 (Client would pick a random number to display)
BP: 100-130 (Client would pick a random number to display)
SpO2: 96-100 (Client would pick a random number to display)
Respiratory distress: Normal
Perfusion: Normal

>Player Mildly Hypovolemic:
HR: 60-110 (Client would pick a random number to display)
BP: 80-100 (Client would pick a random number to display)
SpO2: 94-98 (Client would pick a random number to display)
Respiratory distress: Mild
Perfusion: Borderline

>Player Deceased
HR: ???
BP: ???
SpO2: ???
Respiratory distress: None
Perfusion: None

These vital signs WILL NOT influence the trend of a patient like in ACE 3 (for example if a vital sign hits a certain number it will not trigger anything). instead depending on what variables would be active in a patient, would determine what the client checking the vital signs would see. it doesn't need to stay consistent the numbers can be randomised each time a player checks them.

This should hopefully decrease the strain on the server as it is not spending updates 50 times a second, but still simulate the act of checking vital signs with some reliability. by adding this as a base line, future injuries can be simulated with this system for the future.

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/issues/11

Similar to
